In [1]:
import pandas as pd
import plotly.express as px
import numpy as np
from sklearn.model_selection import train_test_split
from sklearn.model_selection import train_test_split

In [2]:
df = pd.read_csv("data_pipeline/merge_data/flap.csv", index_col = [0])
df.head()

    time    aX    aY    aZ     gX      gY    gZ activity
0  947.0 -0.95 -0.49  0.13  96.07  -62.50 -0.18     flap
1  956.0 -0.95 -0.50  0.23  94.54  -93.75 -0.18     flap
2  961.0 -0.94 -0.52  0.26  93.38 -109.38 -0.18     flap
3  969.0 -0.89 -0.50  0.26  89.42 -140.62 -0.18     flap
4  977.0 -0.84 -0.44  0.19  85.39 -156.25 -0.18     flap

In [3]:
def gestureMagnitudeShifting(training,accel_sets, fract):
    magnitudedf=pd.DataFrame(columns=['activity','aX','aY','aZ'])
    for idx1, aset in enumerate(accel_sets):
        for molecule, denominator in fract:
            magSeries = pd.Series(data={'activity': training['activity'][idx1],
                                    'acceleration':(np.array(aset, dtype=np.float32) * 
                                                    molecule / denominator).tolist()})
            magnitudedf_temp=pd.DataFrame([magSeries])
            magnitudedf=pd.concat([magnitudedf,magnitudedf_temp], ignore_index=True) 
    return magnitudedf

In [4]:
shiftingFractions=[(3, 2), (5, 3), (2, 3), (3, 4), (9, 5), (6, 5), (4, 5)]
accel  = df.iloc[:150,1:4].to_numpy()

files =[]
completedf = pd.DataFrame(columns=['gesture','acceleration'])
df_temp = pd.read_csv("data_pipeline/merge_data/flap.csv", index_col = [0])
x=df_temp[['aX','aY','aZ']].to_numpy()
series = pd.Series(data={'gesture': df['activity'], 'acceleration':x.tolist()})
df_temp2= pd.DataFrame([series])
completedf=pd.concat([completedf,df_temp2], ignore_index=True)  
completedf.head()

In [5]:
def splitDataSets(data, training_ratio, validation_ratio, testing_ratio):
    train_set, test_set = train_test_split(data, test_size=1 - training_ratio, random_state=42)
    val_set, test_set = train_test_split(test_set, test_size=test_ratio/(testing_ratio + validation_ratio), random_state=42) 
    print('len of train_set: '+ str(len(train_set)))
    print('len of test_set: '+ str(len(test_set)))
    print('len of val_set: '+ str(len(val_set)))

    return train_set, val_set, test_set

train_ratio = 0.75
val_ratio = 0.15
test_ratio = 0.10
trainingData, validationData, testingData = splitDataSets(df, train_ratio, val_ratio, test_ratio)

In [49]:
def time_wrapping(molecule, denominator, data):
    """Generate (molecule/denominator)x speed data."""
    tmp_data = [[0 for i in range(len(data[0]))] 
                for j in range((int(len(data) / molecule) - 1) * denominator)]
    
 #  print(tmp_data)
    
    
    for i in range(int(len(data) / molecule) - 1):
        for j in range(len(data[i])):
            for k in range(denominator):
                tmp_data[denominator * i +
                         k][j] = (data[molecule * i + k][j] * (denominator - k) +
                                  data[molecule * i + k + 1][j] * k) / denominator
    return tmp_data

In [53]:
timedf=pd.DataFrame(columns=['gesture','acceleration'])
for idx1, aset in enumerate(accel):
    shiftedAccels =[]
    for molecule, denominator in shiftingFractions:
        shiftedAccels=time_wrapping(molecule, denominator, aset)
       # print(shiftedAccels)
        timeSeries = pd.Series(data={'gesture': df['activity'][idx1],
                                 'acceleration':shiftedAccels})
        timedf_temp=pd.DataFrame([timeSeries])
        timedf=pd.concat([timedf,timedf_temp], ignore_index=True)

[]
[]
[]
[]
[]
[]
[]
[]
[]
[]
[]
[]
[]
[]
[]
[]
[]
[]
[]
[]
[]
[]
[]
[]
[]
[]
[]
[]
[]
[]
[]
[]
[]
[]
[]
[]
[]
[]
[]
[]
[]
[]
[]
[]
[]
[]
[]
[]
[]
[]
[]
[]
[]
[]
[]
[]
[]
[]
[]
[]
[]
[]
[]
[]
[]
[]
[]
[]
[]
[]
[]
[]
[]
[]
[]
[]
[]
[]
[]
[]
[]
[]
[]
[]
[]
[]
[]
[]
[]
[]
[]
[]
[]
[]
[]
[]
[]
[]
[]
[]
[]
[]
[]
[]
[]
[]
[]
[]
[]
[]
[]
[]
[]
[]
[]
[]
[]
[]
[]
[]
[]
[]
[]
[]
[]
[]
[]
[]
[]
[]
[]
[]
[]
[]
[]
[]
[]
[]
[]
[]
[]
[]
[]
[]
[]
[]
[]
[]
[]
[]
[]
[]
[]
[]
[]
[]
[]
[]
[]
[]
[]
[]
[]
[]
[]
[]
[]
[]
[]
[]
[]
[]
[]
[]
[]
[]
[]
[]
[]
[]
[]
[]
[]
[]
[]
[]
[]
[]
[]
[]
[]
[]
[]
[]
[]
[]
[]
[]
[]
[]
[]
[]
[]
[]
[]
[]
[]
[]
[]
[]
[]
[]
[]
[]
[]
[]
[]
[]
[]
[]
[]
[]
[]
[]
[]
[]
[]
[]
[]
[]
[]
[]
[]
[]
[]
[]
[]
[]
[]
[]
[]
[]
[]
[]
[]
[]
[]
[]
[]
[]
[]
[]
[]
[]
[]
[]
[]
[]
[]
[]
[]
[]
[]
[]
[]
[]
[]
[]
[]
[]
[]
[]
[]
[]
[]
[]
[]
[]
[]
[]
[]
[]
[]
[]
[]
[]
[]
[]
[]
[]
[]
[]
[]
[]
[]
[]
[]
[]
[]
[]
[]
[]
[]
[]
[]
[]
[]
[]
[]
[]
[]
[]
[]
[]
[]
[]
[]
[]
[]
[]
[]
[]
[]
[]
[]
[]
[]
[]
[]
[]
[]
[]
[]
[]
[]
[]
[]
[]
[]
[]
[]
[]
[]
[]
[]
[]
[]
[]
[]
[]
[]
[]
[]
[]
[]
[]
[]
[]
[]
[]
[]
[]
[]
[]
[]
[]
[]
[]
[]
[]
[]
[]
[]
[]
[]
[]
[]
[]
[]
[]
[]
[]
[]
[]
[]
[]
[]
[]
[]
[]
[]
[]
[]
[]
[]
[]
[]
[]
[]
[]
[]
[]
[]
[]
[]
[]
[]
[]
[]
[]
[]
[]
[]
[]
[]
[]
[]
[]
[]
[]
[]
[]
[]
[]
[]
[]
[]
[]
[]
[]
[]
[]
[]
[]
[]
[]
[]
[]
[]
[]
[]
[]
[]
[]
[]
[]
[]
[]
[]
[]
[]
[]
[]
[]
[]
[]
[]
[]
[]
[]
[]
[]
[]
[]
[]
[]
[]
[]
[]
[]
[]
[]
[]
[]
[]
[]
[]
[]
[]
[]
[]
[]
[]
[]
[]
[]
[]
[]
[]
[]
[]
[]
[]
[]
[]
[]
[]
[]
[]
[]
[]
[]
[]
[]
[]
[]
[]
[]
[]
[]
[]
[]
[]
[]
[]
[]
[]
[]
[]
[]
[]
[]
[]
[]
[]
[]
[]
[]
[]
[]
[]
[]
[]
[]
[]
[]
[]
[]
[]
[]
[]
[]
[]
[]
[]
[]
[]
[]
[]
[]
[]
[]
[]
[]
[]
[]
[]
[]
[]
[]
[]
[]
[]
[]
[]
[]
[]
[]
[]
[]
[]
[]
[]
[]
[]
[]
[]
[]
[]
[]
[]
[]
[]
[]
[]
[]
[]
[]
[]
[]
[]
[]
[]
[]
[]
[]
[]
[]
[]
[]
[]
[]
[]
[]
[]
[]
[]
[]
[]
[]
[]
[]
[]
[]
[]
[]
[]
[]
[]
[]
[]
[]
[]
[]
[]
[]
[]
[]
[]
[]
[]
[]
[]
[]
[]
[]
[]
[]
[]
[]
[]
[]
[]
[]
[]
[]
[]
[]
[]
[]
[]
[]
[]
[]
[]
[]
[]
[]
[]
[]
[]
[]
[]
[]
[]
[]
[]
[]
[]
[]
[]
[]
[]
[]
[]
[]
[]
[]
[]
[]
[]
[]
[]
[]
[]
[]
[]
[]
[]
[]
[]
[]
[]
[]
[]
[]
[]
[]
[]
[]
[]
[]
[]
[]
[]
[]
[]
[]
[]
[]
[]
[]
[]
[]
[]
[]
[]
[]
[]
[]
[]
[]
[]
[]
[]
[]
[]
[]
[]
[]
[]
[]
[]
[]
[]
[]
[]
[]
[]
[]
[]
[]
[]
[]
[]
[]
[]
[]
[]
[]
[]
[]
[]
[]
[]
[]
[]
[]
[]
[]
[]
[]
[]
[]
[]
[]
[]
[]
[]
[]
[]
[]
[]
[]
[]
[]
[]
[]
[]
[]
[]
[]
[]
[]
[]
[]
[]
[]
[]
[]
[]
[]
[]
[]
[]
[]
[]
[]
[]
[]
[]
[]
[]
[]
[]
[]
[]
[]
[]
[]
[]
[]
[]
[]
[]
[]
[]
[]
[]
[]
[]
[]
[]
[]
[]
[]
[]
[]
[]
[]
[]
[]
[]
[]
[]
[]
[]
[]
[]
[]
[]
[]
[]
[]
[]
[]
[]
[]
[]
[]
[]
[]
[]
[]
[]
[]
[]
[]
[]
[]
[]
[]
[]
[]
[]
[]
[]
[]
[]
[]
[]
[]
[]
[]
[]
[]
[]
[]
[]
[]
[]
[]
[]
[]
[]
[]
[]
[]
[]
[]
[]
[]
[]
[]
[]
[]
[]
[]
[]
[]
[]
[]
[]
[]
[]
[]
[]
[]
[]
[]
[]
[]
[]
[]
[]
[]
[]
[]
[]
[]
[]
[]
[]
[]
[]
[]
[]
[]
[]
[]
[]
[]
[]
[]
[]
[]
[]
[]
[]
[]
[]
[]
[]
[]
[]
[]
[]
[]
[]
[]
[]
[]
[]
[]
[]
[]
[]
[]
[]
[]
[]
[]
[]
[]
[]
[]
[]
[]
[]
[]
[]
[]
[]
[]
[]
[]
[]
[]
[]
[]
[]
[]
[]
[]
[]
[]
[]
[]
[]
[]
[]
[]
[]
[]
[]
[]
[]
[]
[]
[]
[]
[]
[]
[]
[]
[]
[]
[]
[]
[]
[]
[]
[]
[]
[]
[]
[]
[]
[]
[]
[]
[]
[]
[]
[]
[]
[]
[]
[]
[]
[]
[]
[]
[]
[]
[]
[]
[]
[]
[]
[]
[]
[]
[]
[]
[]
[]
[]
[]
[]

In [48]:
df.head()

    time    aX    aY    aZ     gX      gY    gZ activity
0  947.0 -0.95 -0.49  0.13  96.07  -62.50 -0.18     flap
1  956.0 -0.95 -0.50  0.23  94.54  -93.75 -0.18     flap
2  961.0 -0.94 -0.52  0.26  93.38 -109.38 -0.18     flap
3  969.0 -0.89 -0.50  0.26  89.42 -140.62 -0.18     flap
4  977.0 -0.84 -0.44  0.19  85.39 -156.25 -0.18     flap

In [9]:
df_copy = magnitudedf.copy()
df_copy["aX"] = df_copy["acceleration"].apply(lambda i:i[0])
df_copy["aY"] = df_copy["acceleration"].apply(lambda i:i[1])
df_copy["aZ"] = df_copy["acceleration"].apply(lambda i:i[2])

In [16]:
df_copy.tail()

,activity,acceleration,aX,aY,aZ
1045,flap,"[-0.006666666362434626, 0.07999999821186066, -...",-0.006667,0.080,-0.1000
1046,flap,"[-0.007499999832361937, 0.08999999612569809, -...",-0.007500,0.090,-0.1125
1047,flap,"[-0.017999999225139618, 0.21599999070167542, -...",-0.018000,0.216,-0.2700
1048,flap,"[-0.012000000104308128, 0.14399999380111694, -...",-0.012000,0.144,-0.1800
1049,flap,"[-0.007999999448657036, 0.09600000083446503, -...",-0.008000,0.096,-0.1200

In [17]:
df_copy.groupby("activity").mean()

                aX        aY       aZ
activity
flap     -0.717853 -0.369426 -0.72432

In [18]:
df.groupby("activity").mean()

,time,aX,aY,aZ,gX,gY,gZ
activity,,,,,,,
flap,33048.521759,-0.659487,-0.295298,-0.212133,1.190625,10.16019,-7.84918